### ISSUE TITLE
Is it possible to add SpookyX directly to a installation of foolfuuka?

### ISSUE THREAD

**Issue by Lolnada** [Fiddlekins/SpookyX#6] opened 2015-10-30 01:27 UTC
I'm working on a small IB using FoolFuuka. Is it possible to integrate directly SpookyX to it  without any *monkey?

Sorry for my bad English.

**Comment by Fiddlekins** [comment] 2015-10-30 09:25
I don't know much about that I'm afraid but my understanding is that the FoolFuuka control panel has an option to add JavaScript that will be included when serving users the site.

You should be able to use any version of SpookyX in this way, though since the metadata at the top will be ignored there's a couple of caveats:
- it will not check for updates automatically, that's a grease/tampermonkey feature
- there are a couple of external JS files that SpookyX retrieves and inserts into the page before it runs. These will also need to be added
- this may be a non-issue, but SpookyX will need to be loaded after jQuery is else it will fail

If you do get this working please let me know how the process works, as I've had someone else ask me about this before.

**Comment by Lolnada** [comment] 2015-11-03 20:50
I added all the necessary .JS, but not worked. Just appeared the "Settings" link but nothing works.

Any ideas?

**Comment by Fiddlekins** [comment] 2015-11-03 23:12
Give me a link to the site and I'll have a poke around to see if I can work out what's wrong.

**Comment by Lolnada** [comment] 2015-11-03 23:37
http://www.tablachan.org
Is password-protected, use this login:
passphrase: lain
password: 123

Besides SpookyX, i inserted:
jquery.selection.js
query.mousewheel.min.js
colz.class.min.js

**Comment by Fiddlekins** [comment] 2015-11-03 23:49
Okay, give the new v32.34 a spin.
The issue was being caused by the settings menu relying on a variable that tamper/greasemonkey provides that I was using to automatically get the version number, rather than having to manually update it each time.

**Comment by Fiddlekins** [comment] 2015-11-03 23:59
Okay, that's fixed one thing, revealed another that's broken. Gimme a coupla mins.

**Comment by Fiddlekins** [comment] 2015-11-04 00:04
Rather than make a load of incremental versions to sort through this I figure it's best I just give you a pastebin until I get it working. Here's something that should fix an issue with image hover: http://pastebin.com/t5jDzu1s

**Comment by Lolnada** [comment] 2015-11-04 20:19
Thanks! almost everything seems to be working now

**Comment by Fiddlekins** [comment] 2015-11-05 09:29
If you head to a foolfuuka board that is being used as an archive you'll find a strip along the top that contains the links to all the boards - the '.letters' element. It's this element that I hook into when adding things like post/image count, it's this element that has its height checked when working out how to display hovered images, etc

The simplest solution might just be to add it back in, but I'll give this some more thought when I get some time.

**Comment by Fiddlekins** [comment] 2015-11-08 16:13
Okay, give this a shot: http://pastebin.com/tCWPn9NQ

**Comment by Fiddlekins** [comment] 2015-12-01 17:00
Welp, by virtue of the site no longer being up I'm going to close this. From what I could see it also worked.

**Closed by Fiddlekins** 2015-12-01 17:00 UTC
